version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    command: ['ng','serve','--host','0.0.0.0']
    container_name: 'project-frontend'
    ports:
      - '4200:4200'
    volumes:
      - './src:/app/src:delegated'
      - './package.json:/app/package.json:delegated'
      - './node_modules:/app/node_modules:delegated'

networks:
  default:
    external: true
    name: backend
